# 端口号
server:
  port: 9101
  servlet:
    context-path: /webdemo

# actuator 应用监控
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
com:
  castile:
    oss:
      enabled: true
      access-key: 5pBxT3GHOvzG3J5oaBvB
      endpoint: http://localhost:9010
      secret-key: xghdsdd8f8YcZuVTialXG6e0w7QeAV2ErNEut4tU
    zk:
      zk-servers: zookeeper.nifi-docker-compose.orb.local:2181
      connection-timeout: 6000
      max-retries: 5
      session-timeout: 60000
      base-sleep-time: 1000

